title: Open Magic Blog
description: My personal blog website
theme: just-the-docs

url: https://3406088084.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
